service: fifinha

provider:
  name: aws
  runtime: nodejs12.x

custom:
  stepFunctionsOffline:
    BuyPlayer: buyplayer
    SellPlayer: sellplayer

functions:
  buyplayer:
    handler: handler.buyPlayer
    timeout: 29 # optional, in seconds, default is 6
    memorySize: 128
  
  sellplayer:
    handler: handler.sellPlayer
    timeout: 29 # optional, in seconds, default is 6
    memorySize: 128

stepFunctions:
  stateMachines:
    fifinha:
      name: fifinha-${opt:stage}
      type: EXPRESS
      events:
        - http:
            path: fifinha
            method: POST
      definition:
        Comment: "Buy/Sell Players"
        StartAt: BuyPlayer
        States:
          BuyPlayer:
            Type: Task
            Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-buyplayer"
            Next: SellPlayer
          SellPlayer:
            Type: Task
            Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-sellplayer"
            End: true

plugins:
  - serverless-step-functions-offline
  - serverless-pseudo-parameters
  - serverless-step-functions